---
- name: install rsyslog plugins
  apt:
    update_cache: true
    name: "{{ item }}"
    state: present
  loop:
    - rsyslog-elasticsearch
  notify:
    - restart rsyslog

- name: Copy rsyslog conf files
  copy:
    src: "{{ item.src_file }}"
    dest: "{{ item.dest_file }}"
    mode: 0644
  loop:
    # - { src_file: "rsyslog.conf", dest_file: "/etc/rsyslog.conf" }
    # - { src_file: "10-numdub.conf", dest_file: "/etc/rsyslog.d/10-numdub.conf" }
    - {
        src_file: "10-remote-logger.conf",
        dest_file: "/etc/rsyslog.d/10-remote-logger.conf",
      }
  notify:
    - restart rsyslog
  tags:
    - rsyslog-server_copyconf
